version: "3.8"
services:
  db:
    image: postgres
    container_name: githubask_db
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
  #    volumes:
  #      - local_pgdata:/var/lib/postgresql/data
  #      - ./db/init/sql:/docker-entrypoint-initdb.d/create_tabels.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_2
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin